const levels = [
  {
    id: 'signal-order',
    number: '01',
    title: 'The broken signal',
    goal: 'Fabricate your own route through the wall, collect three bits, order the cargo 1 → 0 → 1 and press Enter at DEST.',
    lesson: 'Lithography can paint any region. Etch lowers patterned terrain, Deposit raises it, CMP flattens it to a target height, and Ctrl+Z undoes the last stroke.',
    target: '101',
    start: { x: -5.2, y: -3.7 },
    destination: { x: 5.2, y: 3.7 },
    pickups: [
      { id: 'bit-1a', value: 1, x: -3.6, y: -2.4 },
      { id: 'bit-0', value: 0, x: -0.8, y: 0.1 },
      { id: 'bit-1b', value: 1, x: 2.1, y: 2.1 },
    ],
    obstacles: [],
    gates: [],
    fabrication: { terrain: true },
  },
  {
    id: 'open-channel',
    number: '02',
    title: 'Open the channel',
    goal: 'Load signal 1, then use Lithography and Etch to open the blocked route.',
    lesson: 'Simplified game model: pattern the highlighted barrier, then remove it. These buttons act immediately; movement never changes mode.',
    target: '1',
    start: { x: -4.8, y: -3.7 },
    destination: { x: 4.8, y: 3.7 },
    pickups: [{ id: 'route-bit', value: 1, x: -2.9, y: -2.5 }],
    obstacles: [
      { id: 'left-wall', x: -4.4, y: 0, width: 4.4, height: 0.65, permanent: true },
      { id: 'channel', x: 0, y: 0, width: 4.4, height: 0.65, fabricationTarget: true },
      { id: 'right-wall', x: 4.4, y: 0, width: 4.4, height: 0.65, permanent: true },
    ],
    gates: [],
    fabrication: {
      targetId: 'channel',
      lithography: { processSteps: 1, energy: 3 },
      etch: { processSteps: 1, energy: 4 },
    },
  },
  {
    id: 'invert-signal',
    number: '03',
    title: 'Invert the bit',
    goal: 'Collect the 0, walk the carrier straight through the NOT gate, then deliver the flipped 1 at DEST with Enter.',
    lesson: 'A NOT gate is a pass-through: crossing it flips every carried bit. Nothing has to be placed into it.',
    target: '1',
    start: { x: -5, y: -3.6 },
    destination: { x: 5, y: 3.6 },
    pickups: [{ id: 'not-zero', value: 0, x: -3.5, y: -2.2 }],
    obstacles: [],
    gates: [
      { id: 'not-gate', type: 'NOT', x: 0, y: 0 },
    ],
    fabrication: null,
  },
  {
    id: 'dual-input',
    number: '04',
    title: 'Resolve two inputs',
    goal: 'Load a 1 into each physical AND input port, collect the new output bit from OUT, then deliver it at DEST.',
    lesson: 'The two input bits are consumed when AND fires. A new output bit appears at OUT; walk over it to collect it.',
    target: '1',
    start: { x: -5.1, y: -3.7 },
    destination: { x: 5.1, y: 3.7 },
    pickups: [
      { id: 'and-one-a', value: 1, x: -3.8, y: -2.4 },
      { id: 'and-zero-decoy', value: 0, x: -2.1, y: 2.4 },
      { id: 'and-one-b', value: 1, x: 1.5, y: -2.5 },
    ],
    obstacles: [],
    gates: [
      {
        id: 'and-gate',
        type: 'AND',
        x: 0.4,
        y: 0.7,
        inputs: [
          { id: 'a', label: 'A' },
          { id: 'b', label: 'B' },
        ],
      },
    ],
    fabrication: null,
  },
];

export default levels;
