const wall = (colStart, colEnd = colStart, height = 2, material = 'oxide') => ({
  rows: [0, 11],
  cols: [colStart, colEnd],
  height,
  material,
});

const levels = [
  {
    id: 'make-a-door',
    number: '01',
    title: 'Make a Door',
    goal: 'Carry the 1 through the oxide wall and deliver it at DEST.',
    lesson: 'Paint a small lithography opening in the wall, then Etch the whole mask. The pattern clears after the process.',
    target: '1',
    start: { x: -5.2, y: -3.2 },
    destination: { x: 5.2, y: 3.2 },
    pickups: [{ id: 'door-one', value: 1, x: -3.7, y: -2.4 }],
    obstacles: [],
    gates: [],
    fabrication: {
      terrain: { regions: [wall(8)] },
      allowedProcesses: ['lithography', 'etch'],
    },
  },
  {
    id: 'dont-over-etch',
    number: '02',
    title: "Don't Over-Etch",
    goal: 'Open a narrow route through the thick oxide wall and deliver the 1.',
    lesson: 'A broad mask works, but every patterned tile costs credits. Try opening only the tiles you need.',
    target: '1',
    start: { x: -5.2, y: -2.9 },
    destination: { x: 5.2, y: 2.9 },
    pickups: [{ id: 'narrow-one', value: 1, x: -3.8, y: -2.1 }],
    obstacles: [],
    gates: [],
    fabrication: {
      terrain: { regions: [wall(8, 9)] },
      allowedProcesses: ['lithography', 'etch'],
    },
  },
  {
    id: 'build-a-bridge',
    number: '03',
    title: 'Build a Bridge',
    goal: 'Cross the trench, carry the 1, and deliver it at DEST.',
    lesson: 'Etch cannot help a trench. Pattern one crossing point and Deposit there to raise it to walkable height.',
    target: '1',
    start: { x: -5.2, y: -3.1 },
    destination: { x: 5.2, y: 3.1 },
    pickups: [{ id: 'bridge-one', value: 1, x: -3.6, y: -2.2 }],
    obstacles: [],
    gates: [],
    fabrication: {
      terrain: { regions: [wall(8, 8, 0, 'silicon')] },
      allowedProcesses: ['lithography', 'deposit'],
    },
  },
  {
    id: 'two-problems-one-mask',
    number: '04',
    title: 'Two Problems, One Mask',
    goal: 'Collect 1 then 0, cross both oxide walls, and deliver signal 10.',
    lesson: 'One lithography mask can contain disconnected regions. Pattern openings in both walls before running a single Etch.',
    target: '10',
    start: { x: -5.3, y: -3.1 },
    destination: { x: 5.3, y: 3.1 },
    pickups: [
      { id: 'two-mask-one', value: 1, x: -4.0, y: -2.2 },
      { id: 'two-mask-zero', value: 0, x: -0.2, y: 1.4 },
    ],
    obstacles: [],
    gates: [],
    fabrication: {
      terrain: { regions: [wall(6), wall(11)] },
      allowedProcesses: ['lithography', 'etch'],
    },
  },
  {
    id: 'wrong-side',
    number: '05',
    title: 'The Wrong Side',
    goal: 'Deliver a 1. The direct route passes the wrong bit; find the correct signal instead.',
    lesson: 'Reaching DEST is not enough. If you collect the 0 by mistake, use K to drop it or reorder cargo before delivery.',
    target: '1',
    start: { x: -5.1, y: -3.3 },
    destination: { x: 5.1, y: -3.3 },
    pickups: [
      { id: 'wrong-zero', value: 0, x: 0, y: -3.25 },
      { id: 'wrong-one', value: 1, x: 0, y: 2.7 },
    ],
    obstacles: [
      { id: 'wrong-side-divider', x: 0, y: 0, width: 8.2, height: 1.1, permanent: true },
    ],
    gates: [],
    fabrication: null,
  },
  {
    id: 'etch-or-deposit',
    number: '06',
    title: 'Etch or Deposit?',
    goal: 'Choose your own crossing, carry the 1 through the barrier, and reach DEST.',
    lesson: 'The lower half is raised oxide; the upper half is a trench. Etch one route or Deposit the other. Both are valid.',
    target: '1',
    start: { x: -5.2, y: 0 },
    destination: { x: 5.2, y: 0 },
    pickups: [{ id: 'choice-one', value: 1, x: -3.7, y: 0 }],
    obstacles: [],
    gates: [],
    fabrication: {
      terrain: {
        regions: [
          { rows: [0, 5], cols: [8, 8], height: 2, material: 'oxide' },
          { rows: [6, 11], cols: [8, 8], height: 0, material: 'silicon' },
        ],
      },
      allowedProcesses: ['lithography', 'etch', 'deposit'],
    },
  },
  {
    id: 'cmp-rescue',
    number: '07',
    title: 'CMP Rescue',
    goal: 'Planarize the raised material, carry the 1 across the wafer, and deliver it.',
    lesson: 'CMP is global here: it removes terrain above the chosen plane. Flatten the raised barrier back to height 1.',
    target: '1',
    start: { x: -5.2, y: -3.0 },
    destination: { x: 5.2, y: 3.0 },
    pickups: [{ id: 'cmp-one', value: 1, x: -3.7, y: -2.2 }],
    obstacles: [],
    gates: [],
    fabrication: {
      terrain: {
        regions: [
          wall(8, 8, 2, 'deposit'),
          { rows: [8, 10], cols: [13, 15], height: 2, material: 'deposit' },
        ],
      },
      allowedProcesses: ['cmp'],
    },
  },
  {
    id: 'fabricate-not-route',
    number: '08',
    title: 'Fabricate the NOT Route',
    goal: 'Collect the 0, fabricate a route through the wall, flip it with NOT, and deliver 1.',
    lesson: 'This level combines fabrication and logic. Opening a route is only useful if it leads you to the device that produces the correct signal.',
    target: '1',
    start: { x: -5.2, y: -3.2 },
    destination: { x: 5.2, y: 3.2 },
    pickups: [{ id: 'not-route-zero', value: 0, x: -3.8, y: -2.4 }],
    obstacles: [],
    gates: [{ id: 'not-route-gate', type: 'NOT', x: 1.2, y: 0 }],
    fabrication: {
      terrain: { regions: [wall(7)] },
      allowedProcesses: ['lithography', 'etch'],
    },
  },
];

export default levels;
